### PR TITLE
[NONE] Add test framework and sample test

### PR DESCRIPTION
**Pull request by miniponz**
- Adds Jest and Supertest as well as Jest config
- Adds test script
- Adds sample test in test directory

NOTE: Please pull down this branch and run locally - server is hanging after tests pass and I don't have time to debug today.

### CODE REVIEW

**Comment by bjamba** [comment]
I just added approvals to protect main so we'll wait until changes and then approve this.

**Comment by AaronD87** [comment]
Moving the server to it's own file prevents the hanging after testing. 

The problem is that in index.ts the server is actually started - this means that when the app tests are run your server is started every time index.ts is read (or once per test case)

You can remedy this by splitting the server start logic into a separate file, so that importing index.ts doesn't start the app (rather returns a server instance) @miniponz

**Comment by miniponz** [comment]
> Moving the server to it's own file prevents the hanging after testing.
> 
> The problem is that in index.ts the server is actually started - this means that when the app tests are run your server is started every time index.ts is read (or once per test case)
> 
> You can remedy this by splitting the server start logic into a separate file, so that importing index.ts doesn't start the app (rather returns a server instance) @miniponz

That was high on the list of suspected causes. Usually I'd separate out into `app` and `server` files or something similar. @bjamba since you're the only one who didn't touch this I think you have to approve before it can go in.

**Review by bjamba — APPROVED** [review]
Approving this after discussing with @AaronD87, reviewing, and confirming with @miniponz

**Pull request merged**
